/* =======================================
 \^o^/_______ EJERCICIO 1 ________\^o^/
======================================= */

-------------EJERCIO A
/*
CREATE OR REPLACE FUNCTION Q_JOB(

  J_ID IN JOBS.JOB_ID%TYPE

)

RETURN VARCHAR2

IS

 v_puesto_trab JOBS.JOB_TITLE%TYPE:='';

BEGIN

  SELECT JOB_TITLE INTO v_puesto_trab FROM JOBS 

  WHERE 

  JOB_ID = J_ID;

  RETURN v_puesto_trab;

EXCEPTION

  WHEN NO_DATA_FOUND THEN

    DBMS_OUTPUT.PUT_line('NO EXISTE EL PUESTO DE TRABAJO');

END Q_JOB;
/

*/
-------------EJERCIO B
/*
SET SERVEROUTPUT ON

DECLARE

 G_TITLE JOBS.JOB_TITLE%TYPE;

 J_ID JOBS.JOB_ID%TYPE;

BEGIN

 J_ID:='SA_REP';

 G_TITLE:=Q_JOB(J_ID);

 DBMS_OUTPUT.PUT_LINE('ID TRABAJO: '||J_ID||' - NOMBRE DEL PUESTO DE TRABAJO: '||G_TITLE);

END; */

/* =======================================
 \^o^/_______ EJERCICIO 2 ________\^o^/
======================================= */
--=======================CREANDO LA FUNCION ANUAL_COMP
/*
CREATE OR REPLACE FUNCTION ANNUAL_COMP(

  SUELDO IN EMPLOYEES.SALARY%TYPE:=0,

  P_COMISION IN EMPLOYEES.COMMISSION_PCT%TYPE:=0

)

RETURN NUMBER

IS

 v_anual_compensation EMPLOYEES.SALARY%TYPE:='';

BEGIN

  v_anual_compensation:=(SUELDO*12)+(P_COMISION*SUELDO*12);

  RETURN v_anual_compensation;

END ANNUAL_COMP;

/

--=========================HACIENDO LA CONSULTA SOBRE LA TABLA =======
--SELECT EMPLOYEE_ID, LAST_NAME,ANNUAL_COMP(SALARY,COMMISSION_PCT) FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;
*/


/* =======================================
 \^o^/_______ EJERCICIO 3 ________\^o^/
======================================= */

--==================A)FUNCION VALID_DEPARTID
/*
CREATE OR REPLACE FUNCTION VALID_DEPARTID(

  DEP_ID DEPARTMENTS.DEPARTMENT_ID%TYPE

)

RETURN BOOLEAN

IS

 v_num NUMBER:=0;

 v_bol BOOLEAN:=FALSE;

BEGIN

 SELECT COUNT(*) INTO v_num FROM DEPARTMENTS WHERE DEPARTMENT_ID=DEP_ID;

 IF v_num>0 THEN

  v_bol:=TRUE;

 END IF;

 RETURN v_bol;

END VALID_DEPARTID;

/
*/


/*
---===================B) PROCEDIMIENTO NEW_EMP

CREATE OR REPLACE PROCEDURE NEW_EMP

(

E_NAME IN EMPLOYEES.FIRST_NAME%TYPE,

E_LASTNAME IN EMPLOYEES.LAST_NAME%TYPE,

E_EMAIL IN EMPLOYEES.EMAIL%TYPE,

E_DEP_ID IN EMPLOYEES.DEPARTMENT_ID%TYPE:=30,

E_JOB_ID IN EMPLOYEES.JOB_ID%TYPE:='SA_REP',

E_SALARY IN EMPLOYEES.SALARY%TYPE:=1000,

E_COMM IN EMPLOYEES.COMMISSION_PCT%TYPE:=0,

E_MANG IN EMPLOYEES.MANAGER_ID%TYPE:=145

 )

IS 

 v_temp BOOLEAN:=FALSE;

BEGIN

 v_temp := VALID_DEPARTID(E_DEP_ID);

  

 IF NOT v_temp THEN

  DBMS_OUTPUT.PUT_LINE('EL ID DE DEPARTAMENTO NO ES VALIDO');

 ELSIF v_temp THEN

  INSERT INTO EMPLOYEES(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)

  VALUES

  (EMPLOYEES_SEQ.NEXTVAL, E_NAME,E_LASTNAME,E_EMAIL,NULL,SYSDATE,E_JOB_ID,E_SALARY,E_COMM,E_MANG,E_DEP_ID);

  IF SQL%ROWCOUNT > 0 THEN

   DBMS_OUTPUT.PUT_LINE('EMPLEADO INGRESADO CORRECTAMENTE');

  END IF;

  COMMIT;

 END IF;  

END NEW_EMP;
/
*/

/*
--PRUEBAS

BEGIN

 NEW_EMP('Vigilia','Llanos','vigilia@sgate.com',15);

 NEW_EMP('MIGUEL','SUAREZ','MIGUELSUAREZ@sgate.com',80);

END;

*/
------ HACIENDO CONSULTAS PARA MOSTRAR DATOS INGRESADOS
/*
COLUMN EMPLOYEE_ID FORMAT A5;
COLUMN FIRST_NAME FORMAT A12;
COLUMN LAST_NAME FORMAT A12;
COLUMN EMAIL FORMAT A20;
COLUMN JOB_ID FORMAT A12;
COLUMN SALARY FORMAT A12;
COLUMN DEPARMENT_ID FORMAT A12;
select EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID from EMPLOYEES;
SELECT * FROM EMPLOYEES;
*/